---
- name: Include secret
  include_role:
    name: kubernetes/addons/common/secret

- name: Get an existing CSI driver
  k8s_info:
    api_version: storage.k8s.io/v1beta1
    kind: CSIDriver
  register: csi_driver

- include_tasks: install.yaml
  vars:
    file: "{{ item }}"
  with_items:
    - crds.yaml
    - driver.yaml
    - snapshot-controller.yaml
  when: (csi_driver.resources|length == 0) or (addons.csi.upgrade == true)
