---
- name: Reset Kubernetes component
  command: "kubeadm reset --force"
  register: reset_cluster

- name: Use loadbalancer_address for advertise_address for HA setup
  set_fact:
    advertise_address: "--control-plane-endpoint {{ loadbalancer_address }}"
  when: loadbalancer_address is defined

- name: Use master_ip for advertise_address for non HA setup
  set_fact:
    advertise_address: "--apiserver-advertise-address {{ master_ip }} --apiserver-cert-extra-sans {{ default_network_ip }}"
  when: loadbalancer_address is not defined

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token-ttl 1m \
                 {{ advertise_address }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory
    mode: 0640

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0550
    remote_src: true

- name: Deploy kubernetes dashboard into cluster
  when: init_cluster is succeeded and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
        apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true
