---
- name: Install necessary packages
  apt:
    pkg:
      - apt-transport-https
      - curl
      - ca-certificates
      - software-properties-common
    update_cache: true

- name: Include docker
  include: docker.yaml

- name: Include kubernetes
  include: kubernetes.yaml
