---
- name: Include secret
  include_role:
    name: kubernetes/addons/common/secret

- name: Install external dns
  block:
    - name: Create a external_dns directory if necessary
      file:
        path: "{{ external_dns_path }}"
        state: directory
        mode: 0640

    - name: Generate external dns file
      template:
        src: "external_dns.yaml.j2"
        dest: "{{ external_dns_path }}/external_dns.yaml"
        mode: 0440
      register: external_dns_template

    - name: Create external dns
      command: "kubectl --kubeconfig {{ kubeadmin_config }} apply -f {{ external_dns_path }}/external_dns.yaml"
      when: external_dns_template.changed
