---
- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Join other masters to main master
  when: not kubeadm_ca.stat.exists
  include_tasks: join.yaml

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: true
    state: started
    enabled: true
  register: started_kubelet
